sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - docker build -t plorent/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run plorent/react-test npm test -- --coverage

after_success:
  - docker build -t 060712730170.dkr.ecr.eu-west-1.amazonaws.com/multi-client ./client
  - docker build -t 060712730170.dkr.ecr.eu-west-1.amazonaws.com/multi-nginx ./nginx
  - docker build -t 060712730170.dkr.ecr.eu-west-1.amazonaws.com/multi-server ./server
  - docker build -t 060712730170.dkr.ecr.eu-west-1.amazonaws.com/multi-worker ./worker

  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region us-east-1 | sed 's|https://||')
  - docker push 060712730170.dkr.ecr.eu-west-1.amazonaws.com/multi-client
  - docker push 060712730170.dkr.ecr.eu-west-1.amazonaws.com/multi-nginx
  - docker push 060712730170.dkr.ecr.eu-west-1.amazonaws.com/multi-server
  - docker push 060712730170.dkr.ecr.eu-west-1.amazonaws.com/multi-worker