sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
before_install:
  - openssl aes-256-cbc -K $encrypted_2db2547ff6b5_key -iv $encrypted_2db2547ff6b5_iv -in service-account.json.enc -out service-account.json -d
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t plorent/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true plorent/react-test npm run test