sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_2db2547ff6b5_key -iv $encrypted_2db2547ff6b5_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multik8s-265312
  - gcloud config set compute/zone europe-west4-a
  - gcloud container clusters get-credentials multik8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t plorent/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true plorent/react-test npm run test